madoar/angular-archwizard

README.md
package.json
src/components/components/wizard-navigation-bar.component.horizontal.less
src/components/components/wizard-navigation-bar.component.html
src/components/components/wizard-navigation-bar.component.spec.ts
src/components/components/wizard-navigation-bar.component.vertical.less

This PR fixes the problem, that when defining a wizard step with a title that needs more than one line in vertical mode, the space between the lines is too large, when using a layout with a `large` prefix.
In addition this PR adds the following changes:
- it realigns the css of the horizontal navigation bar layout with the vertical one
- it changes the generic travis badge to a badge showing the build state of the master branch
- it updates the version of `ng2-archwizard` to `1.4.1`
- it sets the text size of the link text in the navigation bar to `14`

Fixing multiline navigation bar links in vertical mode

---

src/components/components/wizard-completion-step.component.ts
src/components/directives/enable-back-links.directive.spec.ts
src/components/directives/enable-back-links.directive.ts
src/components/directives/index.ts
src/components/directives/optional-step.directive.ts
src/components/wizard.module.ts

This PR targets the feature request in #9, where a way is required to make an entered `WizardCompletionStepComponent` exitable.
This has been realized via a new `enableBackLinks` directive that can be added to a `WizardCompletionStepComponent`. This enables a user to leave an entered `WizardCompletionStepComponent` again.

Add an enableBackLinks directive, which enables a user to leave an entered completion step

---

src/components/components/wizard-completion-step.component.ts
src/components/components/wizard-step.component.ts
src/components/directives/enable-back-links.directive.ts
src/components/directives/wizard-completion-step.directive.spec.ts
src/components/directives/wizard-completion-step.directive.ts
src/components/directives/wizard-step.directive.spec.ts
src/components/directives/wizard-step.directive.ts
src/components/util/wizard-completion-step.inferface.ts
src/components/util/wizard-step.interface.spec.ts
src/components/util/wizard-step.interface.ts
src/components/wizard.module.ts

This PR fixes #9 by:
- adding a `wizardStep` directive, which can be used to define a wizard step
- adding a `wizardCompletionStep` directive, which can be used to define a wizard completion step
In addition this PR introduces a new parent class for the wizard completion step, called `WizardCompletionStep`, a few more tests and some documentation changes.

Add two new directives to define a wizard and wizard completion step

---

src/components/components/wizard-navigation-bar.component.horizontal.less
src/components/components/wizard-navigation-bar.component.vertical.less

This PR fixes a few visualization bugs in the navigation bar layouts:
- the length of the line between the steps was to short
- the navigation bar had a small gap between the step circles and the lines
- the font-size for the `small` layout was too small

Fix large empty symbols css

---

README.md
src/components/components/wizard-completion-step.component.spec.ts
src/components/components/wizard-completion-step.component.ts
src/components/components/wizard-step.component.ts
src/components/directives/wizard-completion-step.directive.ts
src/components/directives/wizard-step.directive.ts
src/components/navigation/free-navigation-mode.ts
src/components/navigation/semi-strict-navigation-mode.ts
src/components/navigation/strict-navigation-mode.ts
src/components/util/wizard-step.interface.spec.ts
src/components/util/wizard-step.interface.ts

This PR adds a new `canEnter` input to the wizard steps.
This input is used to check if a wizard step can be entered during step transitions.

Add canEnter input to the wizard steps

---

README.md
src/components/components/wizard.component.spec.ts
src/components/components/wizard.component.ts
src/components/directives/index.ts
src/components/directives/selected.directive.spec.ts
src/components/directives/selected.directive.ts
src/components/navigation/free-navigation-mode.spec.ts
src/components/navigation/free-navigation-mode.ts
src/components/navigation/navigation-mode.interface.ts
src/components/navigation/semi-strict-navigation-mode.spec.ts
src/components/navigation/semi-strict-navigation-mode.ts
src/components/navigation/strict-navigation-mode.spec.ts
src/components/navigation/strict-navigation-mode.ts
src/components/navigation/wizard-state.model.ts
src/components/util/wizard-step.interface.ts
src/components/wizard.module.ts

This PR targets #19.
It introduces a `defaultStepIndex` input for the `WizardComponent`, which takes an optional index of the initial wizard step, which is shown after startup.
In addition it introduces a new `selected` directive, which can be added to a wizard step to indicate, that it is meant as the default step.

Add a way to select a given step after initialisation and reset

---

README.md
src/directives/go-to-step.directive.spec.ts
src/directives/go-to-step.directive.ts
src/directives/next-step.directive.spec.ts
src/directives/next-step.directive.ts
src/directives/previous-step.directive.spec.ts
src/directives/previous-step.directive.ts
src/navigation/free-navigation-mode.spec.ts
src/navigation/free-navigation-mode.ts
src/navigation/navigation-mode.interface.ts
src/navigation/semi-strict-navigation-mode.spec.ts
src/navigation/semi-strict-navigation-mode.ts
src/navigation/strict-navigation-mode.spec.ts
src/navigation/strict-navigation-mode.ts
src/util/wizard-step.interface.spec.ts
src/util/wizard-step.interface.ts

This PR closes #33.
In addition this PR introduces some new outputs for the `goToStep`, `nextStep` and `previousStep` directives, namely:
- `preFinalize`: this event emitter is called directly before the wizard is transitioned
- `postFinalize`: this event emitter is called directly after the wizard is transitioned
- `finalize` this event emitter still exists and functions as a forwarder to `preFinalize`
This PR also removes the now unused methods `canGoToNextStep` and `canGoToPreviousStep`.

Remove duplicate can exit calls

---

README.md
src/components/wizard-navigation-bar.component.spec.ts
src/directives/enable-back-links.directive.spec.ts
src/directives/go-to-step.directive.spec.ts
src/directives/next-step.directive.spec.ts
src/directives/previous-step.directive.spec.ts
src/directives/selected.directive.spec.ts
src/navigation/free-navigation-mode.spec.ts
src/navigation/free-navigation-mode.ts
src/navigation/navigation-mode.interface.ts
src/navigation/semi-strict-navigation-mode.spec.ts
src/navigation/semi-strict-navigation-mode.ts
src/navigation/strict-navigation-mode.spec.ts
src/navigation/strict-navigation-mode.ts
src/util/wizard-completion-step.interface.spec.ts
src/util/wizard-step.interface.spec.ts
src/util/wizard-step.interface.ts

This PR closes #38.
To achieve this, it was necessary to make change the internal step navigation to work via `Promise` objects.

Allow promises in canExit and canEnter inputs

---

README.md
src/directives/optional-step.directive.spec.ts
src/directives/optional-step.directive.ts
src/directives/reset-wizard.directive.spec.ts
src/directives/reset-wizard.directive.ts
src/directives/selected-step.directive.spec.ts
src/directives/selected-step.directive.ts

Fixes #56, by removing the selectors `reset`, `selected` and `optional`

Remove bad directive selectors

---

README.md
src/components/wizard.component.spec.ts
src/components/wizard.component.ts
src/navigation/wizard-state.model.ts

This PR allows:
- the modification of the `defaultStepIndex`, `disableNavigationBar` and navigation mode inputs at runtime
- the insertion and removal of wizard steps after the wizard initialization (except the currently visible step)
Closes #31, #70, #75

Make defaultStepIndex, disableNavigationBar and the navigation mode inputs updatable and allow the insertion/removal of wizard steps

---

README.md
src/directives/go-to-step.directive.spec.ts
src/directives/go-to-step.directive.ts
src/navigation/wizard-state.model.ts
src/util/index.ts
src/util/step-id.interface.spec.ts
src/util/step-id.interface.ts
src/util/step-index.interface.spec.ts
src/util/step-index.interface.ts
src/util/step-offset.interface.spec.ts
src/util/wizard-step.interface.ts

This PR adds a `StepId` and `StepIndex` interface to `ng2-archwizard`.
Both interfaces can be passed to the `awGoToStep` directive as input arguments.
The `StepId` interface enables the wizard to navigate to a step by its unique id, which can be set via the `stepId` input, which all wizard steps support now.
In addition this PR does a bit of refactoring, which includes moving some tests to new test files for the `StepId`, `StepIndex` and `StepOffset` interfaces.
Closes #83

Add StepId and StepIndex interfaces

---

README.md
src/components/wizard-completion-step.component.ts
src/components/wizard-navigation-bar.component.html
src/components/wizard-step.component.ts
src/directives/wizard-completion-step.directive.ts
src/directives/wizard-step.directive.ts
src/util/index.ts
src/util/navigation-symbol.interface.ts
src/util/wizard-step.interface.ts

This PR introduces a new `NavigationSymbol` interface integrating both the fields `navigationSymbol` and `navigationSymbolFontFamily` of the wizard steps.

Introduce a new interface NavigationSymbol

---

src/components/wizard-navigation-bar.component.ts

The current version of `ng2-archwizard` has the bug, that the reversal of the wizard steps in the navigation bar through the usage of the navigation bar direction `right-to-left` leads to an in-place reversal of the wizard steps, instead of a reversal on a copy.
This PR fixes this.

Fix a bug with the reversal of the navigation bar direction

---

README.md

This PR:
- fixes the `[navigationSymbol]` entry in the parameter overview tables
- makes some additional improvements to the readme

Some slight improvements to the readme

---

package.json

This PR removes the npm `prepublish` script, because it hinders npm from publishing the library.

Remove the npm prepublish script

---

angular.json

This PR adds the calculation of the code coverage to npm/ng test

Automatically calculate the code coverage during npm/ng test

---

src/index.ts

Using barrel exports with ng-packagr can have strange side-effects when using the package in an AOT production build. 
This is for issue #131 which I discovered would be fixed by explicitly exporting each component in the index.ts
Since it is impossible to currently write unit tests for Angular AOT builds, I created a small Angular application that used the angular-archwizard package with my changes and verified that the reference to the @ViewChild() component is defined with an AOT build served with Express.js.

Explicitly exporting each component in the base index.ts file

---

README.md
src/lib/components/wizard-navigation-bar.component.html
src/lib/components/wizard-navigation-bar.component.spec.ts

This PR applies the `[stepId]` input field of the `WizardStep`s automatically as the `id` of the `li` elements in the navigation bar. This allows the user to change the navigation button style of individual steps.
@Gevko this should fix #183, it would be nice if you could give it a try to see if it works :)
To set the `id` of the `li` elements in the navigation bar I've used `[attr.id]` instead of `[id]`, because this leads to the removal of the `id` field in the DOM, when `step.stepId``is set to `null` or `undefined`. `[id]` in comparison seems to always add an `id` field to the DOM even if the value is set to `null` or `undefined`.
As far as I know, it seems to be bad practice to use `[attr.id]` instead of `[id]`, but it seems to result in the "cleanest" DOM in this case. Maybe someone …

Apply the [stepId] field from the WizardSteps at ids in the navigation bar

---

tslint.json

```
$ ng lint
Linting "angular-archwizard"...
ERROR: C:/angular-archwizard/src/lib/directives/wizard-step.directive.spec.ts[27, 31]: variable 'WizardStepTestComponent' used before declaration
Lint errors found in the listed files.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
The use of no-use-before-declare rule is now officially discouraged:
- https://palantir.github.io/tslint/rules/no-use-before-declare/
- https://stackoverflow.com/questions/54000528/angular2-tslint-show-variable-xxx-used-before-declaration-when-using-forwardr

In tslint.json, set "no-use-before-declare" to false to prevent linting error

---

src/lib/navigation/base-navigation-mode.interface.ts
src/lib/navigation/semi-strict-navigation-mode.ts
src/lib/navigation/strict-navigation-mode.ts

- Rename `checkReset` to `ensureCanReset`
- Use `void` return value instead of `boolean`
An error is indicated by an exception.
See discussion: https://github.com/madoar/angular-archwizard/pull/166#discussion_r226856010
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/206"><img src="https://gitpod.io/api/apps/github/pbs/github.com/earshinov/angular-archwizard.git/419eb44efbddd2b6b6200bd8b95740e19d8d5e11.svg" /></a>

Rename BaseNavigationMode.checkReset to ensureCanReset

---

package.json

Compatibility range declared in `package.json` is now open-ended (>= 5), corresponding to what is written in README.md.
We have migrated our project where we are using angular-archwizard to Angular 8, and angular-archwizard continued to work just as fine.
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/220"><img src="https://gitpod.io/api/apps/github/pbs/github.com/earshinov/angular-archwizard.git/21a1bbabf5e0cb78224f8072a47cb696069d1978.svg" /></a>

Declare compatibility with Angular 8

---

src/css/wizard-navigation-bar.scss
src/lib/components/wizard-navigation-bar.component.html
src/lib/components/wizard-navigation-bar.component.ts
src/lib/directives/reset-wizard.directive.spec.ts
src/lib/navigation/base-navigation-mode.interface.ts
src/lib/navigation/wizard-navigation-allow-forward.spec.ts
src/lib/navigation/wizard-navigation-with-completion-step.spec.ts
src/lib/navigation/wizard-navigation-with-optional-step.spec.ts
src/lib/navigation/wizard-navigation.spec.ts
src/lib/util/step-id.interface.spec.ts
src/lib/util/step-index.interface.spec.ts
src/lib/util/step-offset.interface.spec.ts
src/lib/util/test-utils.ts
src/lib/util/wizard-step.interface.ts

Solves #213 by following the suggestion from https://github.com/madoar/angular-archwizard/issues/213#issuecomment-501008323
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/221"><img src="https://gitpod.io/api/apps/github/pbs/github.com/earshinov/angular-archwizard.git/2f354a584d4c130eb29928dcbc65ab48e51b01f7.svg" /></a>

Track step "editing" state with a separate `WizardStep.editing` flag

---

README.md
src/lib/directives/navigation-mode.directive.ts
src/lib/navigation/configurable-navigation-mode.ts
src/lib/navigation/wizard-navigation-allow-forward-visited.spec.ts
src/lib/navigation/wizard-navigation-allow-forward.spec.ts
src/lib/navigation/wizard-navigation.spec.ts
src/lib/util/test-utils.ts

This implements another strategy for forward navigation using the navigation bar in addition to `allow` and `deny`. It allows to navigate to a forward step iff the user has visited the step before.
That's a re-implementation of a NavigationMode that we have been using in our project for quite some time. I think it can be useful for other projects as well.
Apart from the code, this MR contains updated unit tests and docs (README).
Shortly I will also prepare a page in the angular-archwizard-demo application.
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/228"><img src="https://gitpod.io/api/apps/github/pbs/github.com/earshinov/angular-archwizard.git/a3998c5c836174f87ca900cb6bf3efe40d3eda7f.svg" /></a>

Support [navigateForward]="visited"

---

README.md
src/css/archwizard.scss
src/css/wizard-navigation-bar.scss

Hello @madoar ,
It is usually considered a good practice of visual design to restrict colors used in the application UI to a limited subset which might be called a palette or a theme. In some cases, such theme lists not only base colors, but also their shades from light to dark to be used in different parts of the UI.
Version 5.0.0 of angular-archwizard exposes SCSS variables which can be used for customizing base colors of the wizard. However, things like using `darken(…, 10%)` to derive a hover color from a base color are still hard coded and hard for a library user to override.
This PR extends angular-archwizard's style customization support. Instead of a small number of variables controlling base colors (`$wz-color-default`, …, `$wz-color-editing`) it exposes a complex `$wz-colors` …

Advanced styles customization

---

src/css/wizard-navigation-bar.scss

This changes the usage of `:before` to `:after` and closes #249
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/252"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/2491eebdd5a0ebc567f110051625837f763cb6b1.svg" /></a>

Change :before to :after

---

README.md
src/lib/components/wizard-navigation-bar.component.html
src/lib/directives/wizard-step-symbol.directive.spec.ts
src/lib/directives/wizard-step-title.directive.spec.ts

This PR closes #251
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/253"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/2c934ca7acb69034c24f1869d56f2f68cdcda027.svg" /></a>

Inject the WizardStep in the "ng-template" Environment of the "awWizardStepSymbol" and "awWizardStepTitle" Directives

---

README.md

This PR:
- adds a short section explaining the usage of the `awCompletedStep` directive to the `README` file
- fixes some comma issues in the `README` file
- improves some other sentences in the `README` file
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/255"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/505d1a3bc08b953f09ce0b087b9bb3a9bbfb7fcb.svg" /></a>

Improvements to the README file

---

.travis.yml

This PR removes Node 11 from the test setup as it has already reached its EOL and adds Node latest (13 at the moment, fail early).
Generally odd major version numbers should not be tested as these are short living release branches. See https://github.com/nodejs/Release#end-of-life-releases
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/259"><img src="https://gitpod.io/api/apps/github/pbs/github.com/DanielRuf/angular-archwizard.git/3f779275bf67491ff79701796b26f55106c7c0fa.svg" /></a>

Test on Node 10, 12 and latest

---

src/lib/directives/go-to-step.directive.ts
src/lib/directives/next-step.directive.ts
src/lib/directives/previous-step.directive.ts
src/lib/directives/reset-wizard.directive.ts
src/lib/util/wizard-step.interface.ts

This PR:
- removes unused parameters of HostListener functions
- adds a missing wort to a comment
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/267"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/cbf730f653d59621209b67c8dcde27da10cc42ff.svg" /></a>

Remove unused HostListener arguments

---

src/css/archwizard.scss

This PR fixes the warnings: 
```
DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$aw-param-indicator-width: null` at the root of the
stylesheet.
╷
273 │   $aw-param-indicator-width: $width !global;
│   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
stdin 273:3   aw-define-style()
stdin 393:13  aw-define-styles()
stdin 600:1   root stylesheet
DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$aw-param-indicator-height: null` at the root of the
stylesheet.
╷
274 │   $aw-param-indicator-height: $height !global;
│   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
stdin 274:3   aw-define-style()
stdin 393:13  aw-define-styles()
stdin 600:1   root stylesheet …
```

Fix the SCSS global variable warnings

---

src/lib/components/wizard.component-nested-steps.spec.ts

This PR:
- adds a more fitting description
- adds some content to the steps in the wizard under test
- adds some checks that compare the actual wizard steps against the detected steps
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/272"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/80ddc0bd417cdb656454dcce3eee2f3255b70ea9.svg" /></a>

Improve the Tests for nested wizard steps

---

README.md

This PR:
- marks string values by adding ' around them
- fixes some indentation issues
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/273"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/e7f3e1be034867e660cf1cddef1ef23388cd8b7f.svg" /></a>

Fix some Issues in the README file

---

README.md

This PR fixes a wrong link in the README file to the `wizard-navigation-bar.scss` file
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/275"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/05ee3c27947bf44c184c86123d227f045b3781d1.svg" /></a>

Fix wrong link in the README file

---

src/css/wizard-navigation-bar.scss

added rtl support to the latest version.
this pr should solve this issue https://github.com/madoar/angular-archwizard/issues/280
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/286"><img src="https://gitpod.io/api/apps/github/pbs/github.com/KarimTayie/angular-archwizard.git/20664ddf3056e9933fdf31ed16feb7e8448c0056.svg" /></a>

added rtl support

---

README.md

This PR cleans up the section `Working with dynamically inserted and removed steps` in the README file.
To be more specific this PR removes the deprecated information that a `ChangeDetectorRef#detectChanges` call may be necessary in the `afterViewInit` lifecycle method.
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/290"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/9253b1fb881dd70c18623034f1d96d7b82271391.svg" /></a>

README Cleanup "Working with dynamically inserted and removed steps"

---

README.md

This PR adds a compatibility matrix that shows which version of `angular-archwizard` is compatible together with which version of Angular
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/320"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/343957b0426f0c3196a0a0b3d2fbe6d085b23079.svg" /></a>

enhancement: add an angular version compatibility matrix
