README.md, src/components/components/wizard-navigation-bar.component.horizontal.less, src/components/components/wizard-navigation-bar.component.html, src/components/components/wizard-navigation-bar.component.spec.ts, src/components/components/wizard-navigation-bar.component.ts, src/components/components/wizard-navigation-bar.component.vertical.less, src/components/components/wizard.component.ts, src/components/navigation/semi-strict-navigation-mode.ts, src/components/navigation/strict-navigation-mode.ts, src/components/navigation/wizard-state.model.ts
This solves #12.
In addition this PR does some refactoring of the code that manages the when text in the navigation bar is shown as a link.
=> Add input to disable navigation bar

README.md
This PR improves the README file.
=> Fix readme tables and do some other readme improvements

README.md, src/components/wizard-navigation-bar.component.spec.ts, src/components/wizard-navigation-bar.component.ts, src/components/wizard.component.html, src/components/wizard.component.ts
=> Enable navigation bar reversal

README.md, src/components/wizard-completion-step.component.css, src/components/wizard-completion-step.component.ts, src/components/wizard-navigation-bar.component.horizontal.less, src/components/wizard-navigation-bar.component.ts, src/components/wizard-navigation-bar.component.vertical.less, src/components/wizard-step.component.css, src/components/wizard-step.component.ts, src/components/wizard.component.less, src/components/wizard.component.ts
This PR closes #27.
Because I wanted to do a rename of the components and directives with a prefix before this PR I couldn't merge PR #46. 
Therefore I created a new PR.
Still most of the credit of this PR goes to @avril-verhaeghen! (Thanks for your help!)
=> Enable custom styles

src/components/wizard-navigation-bar.component.horizontal.less, src/components/wizard-navigation-bar.component.html, src/components/wizard-navigation-bar.component.vertical.less
PR #143 rebased onto `develop` branch.
=> Clickable step indicators + HTML code rework

README.md, package.json
- Add required Angular versions to `peerDependencies`
- Add a short "Compatibility" section to the README
=> Document compatibility with Angular

README.md
This PR adds a short explanation for the `[awWizardStepSymbol]` directive to the README file
=> Update Readme with awWizardStepSymbol explanation

src/lib/util/wizard-step.interface.ts
This PR removes the dependency to `util`
=> Remove the dependency to util

src/lib/components/wizard-navigation-bar.component.vertical.less
Fixes issues from https://github.com/madoar/angular-archwizard/pull/147#issuecomment-429548576
=> Restore vertical nav bar layout, in particular label alignment

package.json
See also https://github.com/madoar/angular-archwizard/issues/163.
=> Declare Angular 7 compatibility in `package.json`

src/index.ts, src/lib/archwizard.module.ts, src/lib/components/wizard-completion-step.component.ts, src/lib/components/wizard-navigation-bar.component.ts, src/lib/components/wizard-step.component.ts, src/lib/components/wizard.component.ts, src/lib/directives/enable-back-links.directive.ts, src/lib/directives/go-to-step.directive.ts, src/lib/directives/index.ts, src/lib/directives/next-step.directive.ts, src/lib/directives/optional-step.directive.ts, src/lib/directives/previous-step.directive.ts, src/lib/directives/reset-wizard.directive.ts, src/lib/directives/selected-step.directive.ts, src/lib/directives/wizard-completion-step.directive.ts, src/lib/directives/wizard-step.directive.ts, src/lib/navigation/free-navigation-mode.ts, src/lib/navigation/index.ts, src/lib/navigation/navigation-mode.provider.ts, src/lib/navigation/semi-strict-navigation-mode.ts, src/lib/navigation/strict-navigation-mode.ts, src/lib/navigation/wizard-state.model.ts, src/lib/util/index.ts, src/lib/util/navigation-symbol.interface.ts, src/lib/util/step-id.interface.ts, src/lib/util/step-index.interface.ts, src/lib/util/step-offset.interface.ts, src/lib/util/wizard-completion-step.interface.ts, src/lib/util/wizard-step.interface.ts
This PR updates the `index.ts` files based on the discussion in #184
=> Update the index.ts files

package-lock.json, package.json, tsconfig.json
This PR updates `angular-archwizard` to use Angular 7
=> Update to angular 7

.gitpod.yml, docker/Dockerfile, karma.conf.js
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/204"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/3096c0b754b1bc0a6b85b2f75bb54c3c60417066.svg" /></a>
=> Add gitpod IDE support

src/lib/navigation/wizard-navigation-allow-forward-visited.spec.ts
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/229"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/585b9b5be62e5ddb3a9f167c30659e9097e0c2be.svg" /></a>
=> Fix missing {static: false} in navigateForward = visited test

package-lock.json, package.json
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/230"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/7e88d6e31884de2b4448897a3f73ca81511d2f8c.svg" /></a>
=> Prepare Version 5.0.0 Release

package.json
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/238"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/cd809a5fb82dd291fb66880ad28f696422a92a72.svg" /></a>
=> Prepare for the next Development Iteration

src/index.ts
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/236"><img src="https://gitpod.io/api/apps/github/pbs/github.com/earshinov/angular-archwizard.git/3aca344237d87ab2de899a306afa8c4910237f0a.svg" /></a>
=> Add WizardStepSymbolDirective to public API (index.ts)

.gitpod.yml, .travis.yml, docker/Dockerfile, karma.conf.js, package-lock.json, package.json
This PR cleans up the karma configuration file and adding firefox as a testing browser.
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/245"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/478fc255cc193362bf545b3d35168369d10fdb00.svg" /></a>
=> Cleanup the Karma Configuration File

README.md, src/lib/directives/optional-step.directive.spec.ts, src/lib/directives/optional-step.directive.ts
This PR closes #246.
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/254"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/ae23616d011ca14e4be5dc77c11dcc74c9286355.svg" /></a>
=> Support making "awOptionalStep" optional

README.md
This PR:
- adds some newlines for better readability
- adds some comments to some code snippets for more information
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/271"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/2dc10e1a4773b0df0c70af436d2fdb03cc7578bd.svg" /></a>
=> Fix some Issues in the README file

package.json
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/276"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/59266f9f1cf2ea9092f73d6b7f3b6bf01121d518.svg" /></a>
=> Prepare Version 6.0.0 Release

package-lock.json, package.json
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/287"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/bde92a2e959b42b8ccb882552036dc09c690569c.svg" /></a>
=> Prepare Version 6.0.1 Release

package-lock.json, package.json
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/293"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/7741e23a0f41683cf293eeb149d3640bd2932458.svg" /></a>
=> Prepare Version 6.1.0 Release

README.md
This PR fixes #300
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/319"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/a448172c31d93e6de6ad253cce5688c5b435b465.svg" /></a>
=> fix: swap defaults of navigateBackward and navigateForward of the [awNavigationMode] directive

package-lock.json, package.json
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/326"><img src="https://gitpod.io/api/apps/github/pbs/github.com/madoar/angular-archwizard.git/fcc39fee6edae3689083012332fa6fb0a742250c.svg" /></a>
=> enhancement: update karma-firefox-launcher dependency
